package com.nt.model;

import lombok.Data;

@Data
public class Employee {

	private Integer empno;
	private String ename;
	private String desg;
	private double salary;
	private Integer deptno;
	
	//gette and setter method is automatically generated by using @Data of lombok api
	/*
	 * public Integer getEmpno() { return empno; } public void setEmpno(Integer
	 * empno) { this.empno = empno; } public String getEname() { return ename; }
	 * public void setEname(String ename) { this.ename = ename; } public String
	 * getDesg() { return desg; } public void setDesg(String desg) { this.desg =
	 * desg; } public double getSalary() { return salary; } public void
	 * setSalary(double salary) { this.salary = salary; } public Integer getDeptno()
	 * { return deptno; } public void setDeptno(Integer deptno) { this.deptno =
	 * deptno; }
	 */

	
}
